INSERT INTO preguntas (texto, correcta) VALUES
('¿Se ha conformado el equipo de proyecto para la implementación del plan?', 'sí'),
('¿Logro conseguir el apoyo de la alta gerencia para la implementación del SGSI?', 'sí'),
('¿Las Políticas y el Manual de la información preparados aplican a toda la organización, es decir colaboradores, clientes y proveedores?', 'sí'),
('¿Las Políticas y el Manual de la Seguridad de la Información fueron aprobados por el equipo del proyecto y la alta dirección?', 'sí'),
('¿El equipo encargado ha revisado y comprendido el Manual de Seguridad de la Información de la organización?', 'sí'),
('¿Realizó la socialización de cada uno de los instrumentos aprobados mediante sesiones de capacitación?', 'sí'),
('¿Organizó los roles del equipo de implementación en compañía del responsable de la organización?', 'sí'),
('¿Efectuó la planificación detallada (actividades y plazos, asignación de roles y preparación del cronograma)?', 'sí'),
('¿Preparó la reunión de inicio (Kick off) y la revisó con el Jefe del Proyecto y/o sponsor?', 'sí'),
('¿Envió la cita para la reunión de kick off una vez validada la presentación?', 'sí'),
('¿Socializó con el jefe de proyecto y/o sponsor el estado de cada entregable?', 'sí'),
('¿Efectuó el levantamiento de riesgos utilizando el cuestionario incluido en la metodología?', 'sí'),
('¿Preparó el documento de devolución (resultados) en base a las respuesta y a las recomendaciones del documento “Resumen de requisitos ISO 27001 y su cumplimiento”?', 'sí'),
('¿Preparó la matriz de riesgo add hoc a la organización?', 'sí'),
('¿Preparó las Políticas de Seguridad de la Información?', 'sí'),
('¿Cada miembro relevante ha aceptado formalmente sus responsabilidades en el cumplimiento de las políticas de seguridad definidas en el manual?', 'sí'),
('¿Se han implementado todas las políticas y procedimientos descritos en el manual en el entorno de trabajo?', 'cumple'),
('¿El personal ha recibido capacitación en línea con los lineamientos del manual para asegurar su comprensión y aplicación?', 'sí'),
('¿Se han identificado y clasificado todos los activos relevantes para la gestión de riesgos de seguridad de la información?', 'sí'),
('¿Se han evaluado todas las amenazas y vulnerabilidades que afectan a los activos identificados?', 'cumple'),
('¿Se ha evaluado cada riesgo en términos de probabilidad e impacto según el plan de gestión?', 'cumple'),
('¿Se han implementado controles de seguridad específicos para mitigar las vulnerabilidades identificadas?', 'sí'),
('¿Se ha conformado la política de la empresa acorde al objetivo de la empresa?', 'sí'),
('¿La política de seguridad de la información ha sido difundida a todo el personal relevante?', 'sí'),
('¿Las políticas de seguridad se aplican de manera consistente en todas las áreas de la organización?', 'sí'),
('¿El Comité de Seguridad de la Información ha sido formalmente establecido con miembros asignados y roles definidos?', 'sí'),
('¿El comité ha asignado claramente las responsabilidades y ha establecido un liderazgo activo en la gestión de seguridad?', 'cumple'),
('¿El comité se reúne periódicamente para revisar el estado de la seguridad de la información, según lo estipulado en el plan?', 'sí'),
('¿El comité realiza análisis de riesgos y toma decisiones sobre controles de mitigación en cada reunión?', 'cumple'),
('¿Se confeccionó una Política de Privacidad y Protección de Datos Personales?', 'sí'),
('¿Todo el personal relevante ha leído y comprende la Política de Privacidad y Protección de Datos Personales?', 'sí'),
('¿Se han implementado controles técnicos y administrativos para proteger los datos personales conforme a la política?', 'sí'),
('¿La política de privacidad se revisa y ajusta regularmente para alinearse con las leyes y normativas vigentes?', 'sí'),
('¿Se ha confeccionado y socializado un plan de ciberseguridad?', 'cumple'),
('¿Se ha realizado una evaluación de la infraestructura tecnológica para identificar posibles vulnerabilidades?', 'sí'),
('¿Se han implementado todas las medidas de protección recomendadas en el plan de ciberseguridad?', 'cumple'),
('¿Todo el personal relevante ha recibido capacitación específica en ciberseguridad y prevención de ataques?', 'sí'),
('¿Se realiza un monitoreo constante de la red y sistemas para detectar posibles amenazas?', 'cumple'),
('¿El plan de ciberseguridad es evaluado y ajustado periódicamente para incorporar nuevas defensas contra amenazas emergentes?', 'sí'),
('¿Logró posicionar al dueño (owner) del SGSI de la organización en su nuevo rol para la continuidad operativa?', 'sí'),
('¿Se han identificado y clasificado todos los activos y recursos críticos para la continuidad operativa?', 'sí'),
('¿Se han establecido y probado procedimientos de respaldo y recuperación de la información?', 'cumple'),
('¿Se confeccionó un Plan de Continuidad Operativa?', 'sí'),
('¿Organizó el comité de seguridad de la información la continuidad operativa?', 'sí'),
('¿Efectuó el cierre de la implementación dejando como sustento al menos un acta de entrega o recepción?', 'sí'),
('¿El personal clave ha sido capacitado en los procedimientos de continuidad operativa?', 'sí'),
('¿El plan de continuidad se revisa y actualiza regularmente para adaptarse a posibles nuevos riesgos?', 'sí'),
('¿El plan de sensibilización y formación en seguridad de la información ha sido definido con objetivos claros y alcanzables?', 'sí'),
('¿Todo el personal relevante ha sido informado sobre el programa y está comprometido a participar?', 'cumple'),
('¿Se han implementado todos los módulos de capacitación según lo establecido en el programa?', 'sí'),
('¿El programa se ajusta periódicamente con base en los resultados de las evaluaciones y el feedback del personal?', 'sí'),
('¿Se han identificado todos los activos críticos y sus vulnerabilidades en el análisis de riesgos?', 'sí'),
('¿Se han evaluado todas las amenazas y sus posibles impactos en los activos identificados?', 'cumple'),
('¿Se han implementado controles efectivos para mitigar los riesgos identificados?', 'sí'),
('¿Existe un proceso de seguimiento regular para los riesgos activos y los controles asociados?', 'cumple'),
('¿El análisis de riesgos se revisa y actualiza regularmente para reflejar cambios en el entorno de seguridad?', 'sí');


SELECT * FROM preguntas;